version: '3'

services:
  knn_model:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./app:/app
      - ./dataset:/dataset
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/ready"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  k6_perf_test:
    image: loadimpact/k6:latest
    platform: "linux/amd64"
    volumes:
      - ./perf_test:/perf_test
    depends_on:
      knn_model: 
        condition: service_healthy
    command: "run /perf_test/perf_test.js --summary-export=/perf_test/perf_results.csv"